[package]
name = "intelli-telemetry-f123"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "intelli-telemetry-f123"
path = "src/main.rs"

[[bin]]
name = "testing"
path = "src/f1-wrapper.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
scylla = "0.8.2"
hyper = "0.14.27"
bincode = "1.3.3"
dotenvy = "0.15.7"
tracing = "0.1.37"
tokio-stream = "0.1.14"
tracing-subscriber = "0.3.17"
tokio = { version = "1.29.1", features = ["full"] }
serde = { version = "1.0.166", features = ["derive"] }
tokio-util = { version = "0.7.8", features = ["codec", "net"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
split-debuginfo = "off"
panic = "abort"
debug = false
