[package]
name = "intelli-telemetry-f123"
version = "0.1.0"
edition = "2021"

[dependencies]
scylla = "0.8.2"
hyper = "0.14.27"
bincode = "1.3.3"
dotenvy = "0.15.7"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tokio = { version = "1.29.1", features = ["full"] }
serde = { version = "1.0.171", features = ["derive"] }
axum = { version = "0.6.19", features = [
    "form",
    "macros",
    "multipart",
    "headers",
] }
chrono = { version = "0.4.26", features = ["serde"] }
thiserror = "1.0.43"
garde = "0.11.2"
serde_trim = "0.4.0"
rs-nanoid = "0.1.0"
rust-argon2 = "1.0.0"
jsonwebtoken = "8.3.0"
redis = { version = "0.23.0", features = ["tokio-comp"] }
lettre = { version = "0.10.4", features = ["tokio1-native-tls", "builder"] }
askama = "0.12.0"
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
tower = { version = "0.4.13", features = [
    "limit",
    "buffer",
    "tokio",
    "timeout",
] }
ahash = "0.8.3"

[profile.release]
debug = 0
lto = "fat"
opt-level = "z"
codegen-units = 1
split-debuginfo = "off"
panic = "abort"
