[package]
name = "intelli-telemetry-f123"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
bincode = "1.3.3"
dotenvy = "0.15.7"
hyper = "0.14.27"
redis = { version = "0.23.0", features = ["tokio-rustls-comp"] }
serde = { version = "1.0.164", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
split-debuginfo = "off"
panic = "abort"
debug = false
